#!/usr/bin/env perl
use strict;
use warnings;
use lib 'lib';
use BN;
use Cairo;
use Getopt::Std qw( getopts );

my %opts;
getopts('n:s:', \%opts);
my $size = $opts{s} || 100;
my $num = $opts{n} || 0;

die unless @ARGV == 1;
my $name = $ARGV[0];
my $anim = BN::Animation->get($name) or die "Can't find animation $name\n";
my $surface = Cairo::ImageSurface->create('argb32', $size, $size);
my $c = Cairo::Context->create($surface);

$c->translate($size/2, $size/2);

my $scale = $anim->render($c, $num, $size, 1, $num);
printf "Scale: %.2fx\n", $scale;

$surface->write_to_png("$name-temp.png");
system("pngcrush -new -brute -q $name-temp.png $name.png") == 0 or die;
unlink "$name-temp.png";
system "open $name.png";

