#!/usr/bin/env perl
# Dump JSON file in a more readable format.
use strict;
use warnings;
use Data::Dump;
use JSON::XS;

foreach my $file (@ARGV) {
   open my $F, '<', $file or die "Can't read $file: $!";
   local $/ = undef;
   my $dat = decode_json(<$F>);
   scrub($dat);
   print "$file\n";
   dd($dat);
   print "\n";
}

sub scrub {
   my $ref = ref($_[0]);
   if ($ref eq 'HASH') {
      scrub($_) foreach values %{$_[0]};
   }
   elsif ($ref eq 'ARRAY') {
      scrub($_) foreach @{$_[0]};
   }
   elsif ($ref eq 'JSON::PP::Boolean' || $ref eq 'JSON::XS::Boolean') {
      $_[0] = ${$_[0]};
   }
}

