#!/usr/bin/env perl
# Main script. Reads game files, dumps wikitext.
# Creates the file data/md5.txt with MD5 hashes of output files, and compares
# against old/md5.txt if it exists. Move data/ to old/ to set the new
# baseline for comparison, and it will tell you what has changed.
use strict;
use warnings;
use lib 'lib';
use BN::Out;

BN::File->promos();
BN::File->update();
BN::Out->write();
BN::Out->show_diffs();

